name: debug

on:
  pull_request:
    branches:
      - next

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Create Comment
        id: create-comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
      - name: Get result
        run: echo "${{steps.create-comment.outputs.result}}"


