name: Node CI
env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: '10.13'
on:
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - '1.x'
      - '2.x'
      - '3.x'
      - '4.x'
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-rust-binding:
    name: Build Rust Binding
    uses: ./.github/workflows/build-rust-binding.yml
    with:
      name: "taro"
  build:
    runs-on: ${{ matrix.os }}
    needs: [build-rust-binding]
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref || github.head_ref || github.ref_name }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Bootstrap project
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: lint
        run: pnpm lint
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: crates/native_binding/artifacts
      - name: Move artifacts
        run: pnpm artifacts
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
        env:
          CI: true
